# Godan server configuration file

[Local]
Host = "0.0.0.0"
Port = "8080"

[Rpcmq]
Host = "rabbitmq"
Port = "5672"
MsgQueue = "rpc-msg-queue" 
ReplyQueue = "rpc-replies-queue" 
Exchange = "rpc-exchange"
ExchangeType = "direct" 

[Monmq]
Host = "rabbitmq"
Port = "5672"
ReplyQueue = "mon-replies" 
Exchange = "mon-exchange"

[DB]
Host = "db"
Port = "3306"
Username = "godan"
Password = "change_this_pwd!"
Name = "godan"
